#!/usr/bin/env bash

data=`cat ~/Library/Application\ Support/Google/Chrome/Default/Bookmarks`
len=$(echo $data | jq .roots.bookmark_bar.children | jq length)
bookmark_list=$(echo $data | jq .roots.bookmark_bar.children)

declare -A datas
names=()
ROW_COUNT=0
FOLDER_COUNT=0

# For progress spinner
i=1
spinner="/-\|"

function bookmark_fzf() {
    echo "Searching for bookmark"
    while [ $ROW_COUNT -lt $len ];
    do
        row_data=$(echo $bookmark_list | jq .[$ROW_COUNT])
        type=$(echo $row_data | jq .type)

        # if the folder type is detected, further inspect itself.
        if [ $type = "\"folder\"" ]; then
            row_len=$(echo $row_data | jq .children | jq length)
            while [ $FOLDER_COUNT -lt $row_len ];
            do
                children_data=$(echo $row_data | jq .children[$FOLDER_COUNT])
                name=$(echo $children_data | jq .name)
                url=$(echo $children_data | jq .url)
                datas[$name]=$url
                names+=("$name")
                (( FOLDER_COUNT++ ))
                # For progress spinner
                printf "\b${spinner:i++%${#spinner}:1}"
            done
        else
            name=$(echo $row_data | jq .name)
            url=$(echo $row_data | jq .url)
            datas[$name]=$url
            names+=("$name")
            # For progress spinner
            printf "\b${spinner:i++%${#spinner}:1}"
        fi
        (( ROW_COUNT++ ))
    done
    
    selected=$(printf "%s\n" "${names[@]}" | fzf)
    selected_link=$(echo ${datas[$selected]} | sed 's/"//g')
    open $selected_link
}

bookmark_fzf
